name = ""
type = "webpack"
account_id = ""
workers_dev = true
webpack_config = "webpack.config.js"
# Only needed for initial deploy, use `wrangler secret put` after first deploy
# vars = {DISCORD_TOKEN="", DISCORD_APPID=""}
